### ISSUE TITLE
[feat] 사장님_예약 관리 구현

### ISSUE THREAD

**Issue by soeunnPark** [Kernel360/E2E2-CATCHLINE#12]
사장님이 영업 중인 식당의 예약을 관리할 수 있습니다.

사용자가 예약 후 실제로 매장에 방문해 이용이 확정되면, 해당 예약의 상태 컬럼을 '방문 완료'로 변경합니다.
불가피한 사유로 방문이 성사되지 않았다면, 해당 예약의 상태 컬럼을 '취소'로 변경 할 수 있습니다. 

- [x] 예약 확정 (방문 예정 -> 방문 완료)
- [x] 예약 거절 (방문 예정 -> 취소)

**Comment by I-migi** [comment]
예약 거절, 확정 기능 구현완료했습니다
