### ISSUE TITLE
[feat] 사장님_웨이팅 관리 구현

### ISSUE THREAD

**Issue by soeunnPark** [Kernel360/E2E2-CATCHLINE#13]
사장님이 영업 중인 식당의 웨이팅 현황을 관리할 수 있습니다.

사용자가 웨이팅 등록 후 매장에 방문이 확정되면, 해당 웨이팅의 상태 컬럼을 '방문 완료'로 변경합니다.
불가피한 사유로 방문을 하지 않았다면, 해당 웨이팅의 상태 컬럼을 '취소'로 변경 할 수 있습니다.

- [x] 웨이팅 확정 (방문 예정 -> 방문 완료)
- [x] 웨이팅 거절 (방문 예정 -> 취소)

**Comment by I-migi** [comment]
웨이팅 확정 및 거절 기능 구현완료했습니다
