### ISSUE TITLE
[feat] 이용 내역 구현

### ISSUE THREAD

**Issue by soeunnPark** [Kernel360/E2E2-CATCHLINE#9]
사용자의 예약/웨이팅 내역을 조회할 수 있다.  
예약과 웨이팅 내역은 방문 예정, 방문 완료, 취소/노쇼로 구분하여 조회할 수 있다.
예약과 웨이팅 취소의 경우 @PatchMapping을 사용해 상태 컬럼의 값을 변경하는 방식을 택했다.
웨이팅은 수정이 불가하며, 예약은 수정이 가능하다.

- [x] 이용내역 전체 조회
- [x] 웨이팅 상세 정보 조회
- [x] 웨이팅 취소
- [x] 예약 상세 정보 조회
- [x] 예약 취소
- [x] 예약 수정

**Comment by I-migi** [comment]
연관관계 설정은 아직 하지 않았습니다 😢
